# localhost 루비 서버 오픈 ( http://localhost:4000 )
# bundle exec jekyll serve
# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 김 주 원 (Juwon-Kim)
title: Junior Web Developer
email: godgod3260@naver.com
# email_title: Email (Email title override)
phone: 010 - 2080 - 3266
# phone_title: Phone (Phone title override)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  juwon-kim
facebook_username: godgod3260
instagram_username: jw93_dev
# Additional icon links
# 여기는 커스터마이징 아이콘 (최우상단)
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Sectionx
# about_title: About Me (Use this to override about section title)
about_profile_image: images/myPicture.jpeg
about_content: | # this will include new lines to allow paragraphs
  3년 차 개발자로 웹 기반 시스템의 개발/배포/운영을 담당하고 있습니다.  <br><br>
  
  판매 시스템 특성 상 잦은 비지니스 로직의 추가/변경으로 인해 코드 분석에 오랜 시간이 걸리는 코드를 개선하고자 <br>
  유지보수가 용이한 코드를 만드는 개발 방법에 대한 것이 최근 관심사입니다. <br><br>
  
  리팩터링을 하다보면 비효율적인 프로세스를 찾을 수 있고,<br> 그것에 대한 개선사항을 먼저 제안하여 효율적인 프로세스를 만든 경험이 있습니다.
   
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 디지털프라자시스템
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: 2020.11.01 ~ now
        quote: >
          디지털프라자 고객/판촉/판매/물류/재무를 위한 시스템
        description: | # this will include new lines to allow paragraphs
          <ul>
            <li>엑셀업로드 로직이 각 Service Layer에서 엑셀 업로드 관련 확장자/파일크기/셀Data추출 등 중복된 로직 Excel Up/Download 처리 클래스 구현으로 개선</li>
            <li>결산/마감 조회 쿼리의 성능 개선</li>
            <li>.Net으로 개발되어 있던 백화점 별 영수증 입수 서버를 JAVA SpringBoot를 통한 API서버로 통합 전환하여
                속도 개선 및 처리로직 일원화</li>
          </ul>
      - layout: left
        title: ITVOC
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: 2019.10.28 ~ 2020.10.31
        quote: >
          Service Request & VOC 처리를 위한 웹
        description: | # this will include new lines to allow paragraphs
          <ul>
            <li>
              하나의 프로젝트에 여러 시스템(VOC처리, 총무, 위험관리, 인사공모)가 구현되어 있어 session-timeout 발생 할 때마다 
              예외처리 화면으로 이동하는 이슈 발견
            </li>
            <li>Session-timeout 예외 발생 시, 각 시스템으로 접속 할 수 있는 root화면을 개발하여 개선</li>
          </ul>
      - layout: left
        title: Wifi 실시간 모니터링
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: 2018.09.02 ~ 2018.11.26
        #additional_links:
        # - title:  Wifi 패킷 실시간 모니터링 웹 서비스 #Github page for project (eg. sproogen/modern-resume-theme)
        #    icon: fab fa-github
        #    url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #  - title:  디지털프라자 시스템 (eg. sproogen/modern-resume-theme)
        #    icon: fab fa-github
        #    url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          KT SI 프로젝트 
        description: | # this will include new lines to allow paragraphs
          <ul>
            <li>오류 패킷을 검출하고 데이터를 표현하기 위한 대용량 데이터 처리</li>
            <li>1,000,000 rows 이상 엑셀 다운로드 1만 단위로 분할하여 임시 파일에 적재 후 일괄 전송 방식을 통한 속도개선</li>
          </ul>
      - layout: left
        title: 영화 흥행 예측 및 맞춤형 추천 웹 서비스
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: 2018.03.02 ~ 2018.07.01
        quote: >
          Java Spring기반 웹 서비스 구현 
        description: | # this will include new lines to allow paragraphs
          <ul>
            <li>데이터 처리를 위한 분산형 처리 시스템 구축(Spark, Hadoop, Redis)</li>
            <li>영화 흥행 예측 요소 분석을 위한 단어사전 학습용 크롤러 구현</li>
            <li>크롤링 데이터와 DB 데이터 간 비교 로직 속도 개선(2중 반복문 -> HashMap & Binary Search)</li>
          </ul>
      - layout: left
        title: 중고 서적 판매 서비스
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: 2016.07.02 ~ 2016.08.31
        quote: >
          ruby on rails를 이용한 CRUD 웹 서비스 구현
        description: | # this will include new lines to allow paragraphs
          <ul>
            <li>게시판 형태의 웹서비스 구현</li>
            <li>pagination 구현</li>
          </ul>
  - title: Experience
    layout: list
    content:
      - layout: right
        title: 삼성SDS
        sub_title: 삼성전자 임직원 시스템 개발 및 유지보수
        caption: 2019.08.05 ~ 현재
        #link: Link to company (optional)
        quote: >
          <ul>
            <li>전자SET운영2팀 고객CI그룹</li>
            <li>사내 알고리즘 SW검정 Pro취득 (im < adv < pro < exp )</li>
          </ul>
        description: | # this will include new lines to allow paragraphs

      - layout: right
        title: Software Maestro 10기
        sub_title: 과학기술정보통신부/정보통신기획평가원 주관
        caption: 2019.04.01 ~ 2019.06.31
        #link: Link to company (optional)
        quote: >

        description: | # this will include new lines to allow paragraphs
          <ul>
            <li>드론 활용 배달 서비스 프로젝트 주제 선정</li>
            <li>프로젝트 멘토/멘티 구성</li>
          </ul>
          
      - layout: right
        title: 멋쟁이 사자처럼 4기
        sub_title: ruby on rails 기반 web 개발 교육 동아리
        caption: 2016.04 ~ 2016.08
        #link: Link to company (optional)
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          <ul>
            <li>2~3개월 간 ruby on rails기반 웹 개발 교육</li>
            <li>각 Chapter이수 후, 단기 프로젝트 진행</li>
            <li>알파오(AI기반 오목) 주제 해커톤 참여</li>
          </ul>

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: 평택대학교
        sub_title: 정보통신학과
        caption: 2011.03 ~ 2018.02
        quote: >
          
        description: | # this will include new lines to allow paragraphs

      - layout: top-right
        title: 정보처리기사
        sub_title: 자격증
        caption: 2016.11 취득
        quote: >
          
        description: | # this will include new lines to allow paragraphs    

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
